trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'serviceconnnection_gmj1'
  EnvironmentType: 'Test'
  ResourceGroupName: 'RG_GMJ3'
  DeploymentDefaultLocation: 'westus3'
  yourName1: 'gmj'

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      location: $(DeploymentDefaultLocation)
      ResourceGroupName: 'rg11'
      csmFile: main2.bicep
